#!/usr/bin/env bash
# Generate a fresh production .env with new secrets (never committed).
# Usage: ./scripts/generate-vps-env.sh [output-path]
# Default output: ~/.landscrape-vps.env
set -euo pipefail

OUT="${1:-$HOME/.landscrape-vps.env}"

rand_hex() { openssl rand -hex "$1"; }

POSTGRES_PASSWORD="$(rand_hex 24)"
MINIO_PASSWORD="$(rand_hex 24)"
INTERNAL_API_KEY="$(rand_hex 32)"
CREDENTIALS_KEY="$(rand_hex 32)"
KEYCLOAK_CLIENT_SECRET="$(rand_hex 32)"
KEYCLOAK_ADMIN_PASSWORD="$(rand_hex 24)"
XACTIONS_POSTGRES_PASSWORD="$(rand_hex 24)"
XACTIONS_JWT_SECRET="$(rand_hex 32)"
XACTIONS_SESSION_SECRET="$(rand_hex 32)"

umask 077
cat >"$OUT" <<EOF
# Generated $(date -u +"%Y-%m-%dT%H:%M:%SZ") — store in GitHub secret VPS_DOTENV only.
# Local copy (gitignored): $OUT

LANDSCRAPE_IMAGE_REGISTRY=ghcr.io
LANDSCRAPE_IMAGE_OWNER=boro-tech-dev
LANDSCRAPE_IMAGE_TAG=prod

POSTGRES_DB=landscrape
POSTGRES_USER=landscrape
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://landscrape:${POSTGRES_PASSWORD}@postgres:5432/landscrape

REDIS_URL=redis://redis:6379

MINIO_ROOT_USER=landscrape
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
STORAGE_ENDPOINT=http://minio:9000
STORAGE_REGION=us-east-1
STORAGE_ACCESS_KEY=landscrape
STORAGE_SECRET_KEY=${MINIO_PASSWORD}
STORAGE_BUCKET=landscrape-artifacts
STORAGE_FORCE_PATH_STYLE=true
STORAGE_PUBLIC_BASE_URL=http://minio:9000

OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_MODEL=llama3.2:3b
OLLAMA_AGENT_MODEL=llama3.2:3b
LANDSCRAPE_OLLAMA_MAX_CONCURRENT=1
LANDSCRAPE_OLLAMA_GLOBAL_MAX_CONCURRENT=2
LANDSCRAPE_OLLAMA_PIPELINE_TIMEOUT_MS=120000

AGENT_PORT=4010
AGENT_INTERNAL_URL=http://agent:4010
LANDSCRAPE_REFERENCE_TOOLS=mcp
LANDSCRAPE_ENRICH_USE_AGENT=false
LANDSCRAPE_AGENT_TURN_CONCURRENCY=1

MCP_FDA_URL=http://mcp-fda:4020
MCP_PUBMED_URL=http://mcp-pubmed:4021
MCP_CLINICALTRIALS_URL=http://mcp-clinicaltrials:4022

NODE_ENV=production
API_PORT=4000
WEB_PORT=3000
ADMIN_PORT=3001

LANDSCRAPE_TENANT_SLUG=ayvakit
LANDSCRAPE_SEED=true
LANDSCRAPE_INTERNAL_API_KEY=${INTERNAL_API_KEY}

LANDSCRAPE_CONTACT_EMAIL=matt@boro-tech.com
LANDSCRAPE_CONTACT_URL=https://deliver-impact.com

LANDSCRAPE_CREDENTIALS_KEY=${CREDENTIALS_KEY}

NEXT_PUBLIC_API_BASE_URL=https://deliver-impact.com
WEB_PUBLIC_URL=https://deliver-impact.com
API_INTERNAL_URL=http://api:4000
ADMIN_BASE_URL=https://admin.deliver-impact.com

AUTH_ENABLED=true
KEYCLOAK_URL=http://keycloak:8080
KEYCLOAK_REALM=landscrape
KEYCLOAK_CLIENT_ID=landscrape-web
KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
KEYCLOAK_ISSUER=http://keycloak:8080/realms/landscrape
AUTH_COOKIE_DOMAIN=.deliver-impact.com
AUTH_CORS_ORIGINS=https://deliver-impact.com,https://www.deliver-impact.com,https://admin.deliver-impact.com
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

LANDSCRAPE_SCHEDULER_INTERVAL_MS=120000
LANDSCRAPE_SCHEDULER_BURST_LIMIT=3
LANDSCRAPE_EMBED_BACKFILL_INTERVAL_MS=900000
LANDSCRAPE_EMBED_BACKFILL_BATCH_SIZE=5
LANDSCRAPE_EMBED_BACKFILL_MAX_QUEUE_DEPTH=20
LANDSCRAPE_EMBED_BACKFILL_ENABLED=true
LANDSCRAPE_ENRICH_IMPORTANCE_THRESHOLD=88
LANDSCRAPE_PRODUCT_ENRICH_ENABLED=false
LANDSCRAPE_COMPETITOR_RENDER_MODE=fetch
LANDSCRAPE_LOG_QUEUE_DEPTH=true

LANDSCRAPE_X_BACKEND=api
XACTIONS_API_URL=http://xactions-api:3001
XACTIONS_POSTGRES_PASSWORD=${XACTIONS_POSTGRES_PASSWORD}
XACTIONS_JWT_SECRET=${XACTIONS_JWT_SECRET}
XACTIONS_SESSION_SECRET=${XACTIONS_SESSION_SECRET}
EOF

chmod 600 "$OUT"
echo "Wrote $OUT (mode 600)"
echo "Next:"
echo "  1. Update GitHub secret VPS_DOTENV with this file"
echo "  2. ./scripts/rotate-vps-secrets.sh $OUT"
